version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:12.4
    volumes:
     - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${REM_POSTGRES_DB}
      - POSTGRES_USER=${REM_POSTGRES_USER}
      - POSTGRES_PASSWORD=${REM_POSTGRES_PASSWORD}
      # - PGDATA=/tmp
    ports:
      - 5432:5432
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:11.0.1
    environment:
      - DB_VENDOR=POSTGRES
      - DB_DATABASE=${REM_POSTGRES_DB}
      - DB_SCHEMA=public
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_USER=${REM_POSTGRES_USER}
      - DB_PASSWORD=${REM_POSTGRES_PASSWORD}
      - KEYCLOAK_USER=${REM_KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${REM_KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - ldap
  ldap:
    container_name: ldap
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=${REM_LDAP_ADMIN_PASSWORD}
    volumes:
      - ./volumes/ldap/var:/var/lib/ldap
      - ./volumes/ldap/etc:/etc/ldap/slapd.d
  ldap-admin:
    container_name: ldap-admin
    image: osixia/phpldapadmin
    ports:
      - 8083:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap