apiVersion: apps/v1
kind: Deployment
metadata:
  name: eclipsefdn-react-membership
  namespace: foundation-internal-webdev-apps
  labels:
    app: eclipsefdn-react-membership
    environment: production
spec:
  selector:
    matchLabels:
      app: eclipsefdn-react-membership
      environment: production
  replicas: 2
  template:
    metadata:
      labels:
        app: eclipsefdn-react-membership
        environment: production
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: speed
                operator: NotIn
                values:
                - fast
            weight: 1
      containers:
      - name: app
        image: eclipsefdn/eclipsefdn-react-membership:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        env: 
        - name: CONFIG_SECRET_PATH
          value: "/run/secrets/react-membership-app/secret.properties"
        volumeMounts:
        - name: secret-properties
          mountPath: "/run/secrets/react-membership-app"
          readOnly: true
      volumes:
      - name: secret-properties
        secret:
          secretName: react-membership-app
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: eclipsefdn-react-membership
  namespace: foundation-internal-webdev-apps
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: eclipsefdn-react-membership
    environment: production
---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  name: eclipsefdn-react-membership
  namespace: foundation-internal-webdev-apps
  annotations:
    haproxy.router.openshift.io/timeout: 20s
    haproxy.router.openshift.io/disable_cookies: "true"
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: "api.eclipse.org"
  path: "/membership"
  port:
    targetPort: "http"
  tls:
    insecureEdgeTerminationPolicy: "Redirect"
    termination: "edge"
  to:
    kind: "Service"
    name: eclipsefdn-react-membership
    weight: 100
